# -*- coding: utf-8 -*-
"""exerc_log_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1egrCRV-jYo3nQSaL7Qz_aHpbUuHyMBzR
"""

num1 = int(input("Digite um número inteiro:"))
num2 = int(input("Digite outro número inteiro:"))

a = [1,2,3]

list(map(lambda x: x**2, a))

soma = num1 + num2
print(f"A soma dos números é {soma}.")

mult = num1 * num2
print(f"A multiplicação dos números é {mult}.")

pot = num1**num2
print(f"O primeiro número elevado ao segundo número é {pot}.")

sub = num1 - num2
print(f"Subtraindo o segundo número do primeiro obtemos {sub}.")



if num1 > num2:
  resto = num1 % num2
  print("O resto da divisão de ", num1, "por", num2, f"é {resto}.")

num = int(input("Digite um número inteiro:"))
while num < 5:
  print("Você digitou um número menor que 5.")
  num = int(input("Digite um número inteiro:"))

